-- AlterTable
ALTER TABLE "Show" ADD COLUMN     "amEndTime" TEXT NOT NULL DEFAULT '12:00',
ADD COLUMN     "amStartTime" TEXT NOT NULL DEFAULT '08:00',
ADD COLUMN     "pmEndTime" TEXT NOT NULL DEFAULT '16:00',
ADD COLUMN     "pmStartTime" TEXT NOT NULL DEFAULT '12:00';
